### ISSUE TITLE
MVP & Schema

### ISSUE THREAD

**Issue by andrewlangston** [dlande000/Fakebook#1]
Hey David,

Good job setting up your fullstack project repo! Moving forward, we will be using Github issues to track outstanding points to addressed (alongside Slack, etc.). Please see below for a few notes regarding your preliminary design documents:

- [x] `users` should also have a column for `birthday` and `gender`, as reflected on Facebook's signup/login page. You may also wish to consider adding profile-based columns such as `bio`, `hometown`, etc. Let's discuss this before next week.
- [x] How will you keep track of where a `post` is posted (i.e., different users' walls, or on their own timeline)?
- [x] Your `comments` table features `comment_id` and `parent_id` foreign keys, but states that `post_id` references `posts` and `parent_id` references `comments`. It also indexes on `author_id` twice.
- [x] `likes` features a `likeable_type` column, which would suggest a polymorphic association. Do you plan to implement this? If so, please add a note detailing what resources will be involved.

Let me know if you have any questions!

**Comment by dlande000** [comment]
Hello Andrew, 

Thank you for providing the comments above. When we talk today, let's please discuss the other points with regards to `users`. I have added the birthday the gender columns. 

With regards to `posts`, I have added a column for `receiver_id`. This will point to the user profile onto which the post is posted. When one posts to one's own profile, the `receiver_id` and `author_id` are the same. 

With regards to `comments`, I have changed `comment_id` to `post_id`; it was meant to be the foreign key of the post onto which a comment is left. I have removed the duplicate `author_id`.

My thinking with the `likes` feature is that I could use the `likeable_type` to interpolate into the URL path; please let me know if you think this approach makes sense, and if I should add the information to my schema. 

I've also edited the `users` table to reflect friendships (as per our Slack discussion), and I added a `friendships` table. 

Thank you for your notes; I will speak with you soon.

**Comment by andrewlangston** [comment]
Thanks for the clarification, David. I think we can pass the `likeable_type` back with `params` rather than as part of our `path`, which will simplify backend routes somewhat. Happy to discuss when we meet today.

**Comment by andrewlangston** [comment]
Hey David,

As we discussed, here are a few more things to address with respect to your MVP timeline and schema: 
- [ ] Default prof pic & banner pic
- [ ] No need to edit users as part of MVP
- [ ] Add bio or similar field to users table for display on timeline

**Comment by dlande000** [comment]
Hello Andrew, 

Thank you for the notes and for meeting with me today. I have updated my user schema and MVP to reflect the changes you noted. Please let me know if there is anything else I should change before using this blueprint. Thank you, and speak with you soon.
